[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
seamless_config = ["tools.yaml"]

[project]
name = "seamless-transformer"
version = "0.0.0"

[project.scripts]
seamless = "seamless_transformer.cmd.main:main"
